table 'Product Subcategories Lookup'
	excludeFromModelRefresh
	lineageTag: 7692cf35-ca1f-46a9-af17-27c7845c338a

	column ProductSubcategoryKey
		dataType: int64
		isKey
		formatString: 0
		lineageTag: 331d4256-a9da-470d-9451-33789417cb77
		summarizeBy: none
		sourceColumn: ProductSubcategoryKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SubcategoryName
		dataType: string
		lineageTag: a8a121c6-66c2-49dc-91b6-ce36a4284034
		summarizeBy: none
		sourceColumn: SubcategoryName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ProductCategoryKey
		dataType: int64
		formatString: 0
		lineageTag: 2a0d4fb1-5520-4651-baa6-93d61ed59b3f
		summarizeBy: none
		sourceColumn: ProductCategoryKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Product Subcategories Lookup' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("E:\DevOP\Pwer BI\AdventureWorks+Raw+Data\AdventureWorks Raw Data\AdventureWorks Product Subcategories Lookup.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ProductSubcategoryKey", Int64.Type}, {"SubcategoryName", type text}, {"ProductCategoryKey", Int64.Type}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

